spring:
  datasource:
    url: "jdbc:mysql://192.168.0.180:3306/icd?useSSL=false&useUnicode=true&characterEncoding=utf8"
    username: 'icredit'
    password: 'icreditDB@2018'
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:com/liucaihao/mapper/*Mapper.xml
